# -*- coding: utf-8 -*-
"""Copy of finalclass1:30Web scrapping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VbcZaXpA_U5BjkIfkiVAEhcqex19G6G4
"""

from bs4 import BeautifulSoup
import requests
url = BeautifulSoup('http://www.nepalstock.com/todaysprice','html.parser')
response = requests.get(url)

output=[]
data = response.text
soup = BeautifulSoup(data,'xml')
soup = soup.table
tag = soup.find_all('tr')
tags = tag[1:]

for i in tags:
  x = i.get_text()
  output.append(x)
output

a = output[1].split('                                             ')
b = a[0:-1]
b

main_output = []
for i in range(1,20):
  x = b[i].split('\n')
  y = x[4:-1]
  main_output.append(y)
print(main_output)

c = b[0].split('\n')
d = c[1:-1]

header = output[0].split('\n')
headers = header[1:-1]
headers

now_output = [headers]+[d]+main_output
print(now_output)

# SN = []
# TC = []
# NT = []
# MP = []
# MinP = []
# for i in range(20):
  
#     sn = now_output[i][0]
#     SN.append(sn)
#     tc = now_output[i][1]
#     TC.append(tc)
#     nt = now_output[i][2]
#     NT.append(nt)
#     mp = now_output[i][3]
    

# data = {'SN':SN,'Traded Companies':TC,'No. Of Transaction':NT}

# import pandas as pd
# df = pd.DataFrame(data)
# df.to_csv('data.csv')

import csv
data = now_output
with open('clas130.csv','a') as f:
  for i in range(20):
    mydata = csv.writer(f)
    mydata.writerow(data[i])